// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/antibruteforce.proto

package apipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{0}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CheckRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CheckRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type CheckResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{1}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ResetRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{2}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

func (m *ResetRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ResetRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ResetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{3}
}

func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type BlacklistAddRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistAddRequest) Reset()         { *m = BlacklistAddRequest{} }
func (m *BlacklistAddRequest) String() string { return proto.CompactTextString(m) }
func (*BlacklistAddRequest) ProtoMessage()    {}
func (*BlacklistAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{4}
}

func (m *BlacklistAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistAddRequest.Unmarshal(m, b)
}
func (m *BlacklistAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistAddRequest.Marshal(b, m, deterministic)
}
func (m *BlacklistAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistAddRequest.Merge(m, src)
}
func (m *BlacklistAddRequest) XXX_Size() int {
	return xxx_messageInfo_BlacklistAddRequest.Size(m)
}
func (m *BlacklistAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistAddRequest proto.InternalMessageInfo

func (m *BlacklistAddRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type BlacklistAddResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistAddResponse) Reset()         { *m = BlacklistAddResponse{} }
func (m *BlacklistAddResponse) String() string { return proto.CompactTextString(m) }
func (*BlacklistAddResponse) ProtoMessage()    {}
func (*BlacklistAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{5}
}

func (m *BlacklistAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistAddResponse.Unmarshal(m, b)
}
func (m *BlacklistAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistAddResponse.Marshal(b, m, deterministic)
}
func (m *BlacklistAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistAddResponse.Merge(m, src)
}
func (m *BlacklistAddResponse) XXX_Size() int {
	return xxx_messageInfo_BlacklistAddResponse.Size(m)
}
func (m *BlacklistAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistAddResponse proto.InternalMessageInfo

func (m *BlacklistAddResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type BlacklistRemoveRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistRemoveRequest) Reset()         { *m = BlacklistRemoveRequest{} }
func (m *BlacklistRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BlacklistRemoveRequest) ProtoMessage()    {}
func (*BlacklistRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{6}
}

func (m *BlacklistRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistRemoveRequest.Unmarshal(m, b)
}
func (m *BlacklistRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BlacklistRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistRemoveRequest.Merge(m, src)
}
func (m *BlacklistRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BlacklistRemoveRequest.Size(m)
}
func (m *BlacklistRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistRemoveRequest proto.InternalMessageInfo

func (m *BlacklistRemoveRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type BlacklistRemoveResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistRemoveResponse) Reset()         { *m = BlacklistRemoveResponse{} }
func (m *BlacklistRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*BlacklistRemoveResponse) ProtoMessage()    {}
func (*BlacklistRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{7}
}

func (m *BlacklistRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistRemoveResponse.Unmarshal(m, b)
}
func (m *BlacklistRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistRemoveResponse.Marshal(b, m, deterministic)
}
func (m *BlacklistRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistRemoveResponse.Merge(m, src)
}
func (m *BlacklistRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_BlacklistRemoveResponse.Size(m)
}
func (m *BlacklistRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistRemoveResponse proto.InternalMessageInfo

func (m *BlacklistRemoveResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type WhitelistAddRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistAddRequest) Reset()         { *m = WhitelistAddRequest{} }
func (m *WhitelistAddRequest) String() string { return proto.CompactTextString(m) }
func (*WhitelistAddRequest) ProtoMessage()    {}
func (*WhitelistAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{8}
}

func (m *WhitelistAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistAddRequest.Unmarshal(m, b)
}
func (m *WhitelistAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistAddRequest.Marshal(b, m, deterministic)
}
func (m *WhitelistAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistAddRequest.Merge(m, src)
}
func (m *WhitelistAddRequest) XXX_Size() int {
	return xxx_messageInfo_WhitelistAddRequest.Size(m)
}
func (m *WhitelistAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistAddRequest proto.InternalMessageInfo

func (m *WhitelistAddRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type WhitelistAddResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistAddResponse) Reset()         { *m = WhitelistAddResponse{} }
func (m *WhitelistAddResponse) String() string { return proto.CompactTextString(m) }
func (*WhitelistAddResponse) ProtoMessage()    {}
func (*WhitelistAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{9}
}

func (m *WhitelistAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistAddResponse.Unmarshal(m, b)
}
func (m *WhitelistAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistAddResponse.Marshal(b, m, deterministic)
}
func (m *WhitelistAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistAddResponse.Merge(m, src)
}
func (m *WhitelistAddResponse) XXX_Size() int {
	return xxx_messageInfo_WhitelistAddResponse.Size(m)
}
func (m *WhitelistAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistAddResponse proto.InternalMessageInfo

func (m *WhitelistAddResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type WhitelistRemoveRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistRemoveRequest) Reset()         { *m = WhitelistRemoveRequest{} }
func (m *WhitelistRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*WhitelistRemoveRequest) ProtoMessage()    {}
func (*WhitelistRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{10}
}

func (m *WhitelistRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistRemoveRequest.Unmarshal(m, b)
}
func (m *WhitelistRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistRemoveRequest.Marshal(b, m, deterministic)
}
func (m *WhitelistRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistRemoveRequest.Merge(m, src)
}
func (m *WhitelistRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_WhitelistRemoveRequest.Size(m)
}
func (m *WhitelistRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistRemoveRequest proto.InternalMessageInfo

func (m *WhitelistRemoveRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type WhitelistRemoveResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistRemoveResponse) Reset()         { *m = WhitelistRemoveResponse{} }
func (m *WhitelistRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*WhitelistRemoveResponse) ProtoMessage()    {}
func (*WhitelistRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbcdaefbc0f163d9, []int{11}
}

func (m *WhitelistRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistRemoveResponse.Unmarshal(m, b)
}
func (m *WhitelistRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistRemoveResponse.Marshal(b, m, deterministic)
}
func (m *WhitelistRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistRemoveResponse.Merge(m, src)
}
func (m *WhitelistRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_WhitelistRemoveResponse.Size(m)
}
func (m *WhitelistRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistRemoveResponse proto.InternalMessageInfo

func (m *WhitelistRemoveResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*CheckRequest)(nil), "api.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "api.CheckResponse")
	proto.RegisterType((*ResetRequest)(nil), "api.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "api.ResetResponse")
	proto.RegisterType((*BlacklistAddRequest)(nil), "api.BlacklistAddRequest")
	proto.RegisterType((*BlacklistAddResponse)(nil), "api.BlacklistAddResponse")
	proto.RegisterType((*BlacklistRemoveRequest)(nil), "api.BlacklistRemoveRequest")
	proto.RegisterType((*BlacklistRemoveResponse)(nil), "api.BlacklistRemoveResponse")
	proto.RegisterType((*WhitelistAddRequest)(nil), "api.WhitelistAddRequest")
	proto.RegisterType((*WhitelistAddResponse)(nil), "api.WhitelistAddResponse")
	proto.RegisterType((*WhitelistRemoveRequest)(nil), "api.WhitelistRemoveRequest")
	proto.RegisterType((*WhitelistRemoveResponse)(nil), "api.WhitelistRemoveResponse")
}

func init() { proto.RegisterFile("api/antibruteforce.proto", fileDescriptor_cbcdaefbc0f163d9) }

var fileDescriptor_cbcdaefbc0f163d9 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x51, 0x4f, 0xea, 0x30,
	0x14, 0xc7, 0x61, 0x04, 0x2e, 0xf7, 0x84, 0x7b, 0x6f, 0x6e, 0x45, 0x9c, 0xd3, 0x44, 0xb3, 0x07,
	0xa3, 0x0f, 0x22, 0x51, 0xbf, 0x00, 0x18, 0x5f, 0x8d, 0x99, 0x0f, 0x26, 0xbe, 0x75, 0xe3, 0x28,
	0xcd, 0x70, 0xad, 0x6b, 0xc1, 0xcf, 0xe4, 0xb7, 0x34, 0x74, 0x75, 0xe9, 0xa0, 0x53, 0x1e, 0xdb,
	0xfe, 0xcf, 0x8f, 0x7f, 0xf8, 0x9d, 0x81, 0x4f, 0x05, 0xbb, 0xa0, 0x99, 0x62, 0x71, 0xbe, 0x50,
	0xf8, 0xcc, 0xf3, 0x04, 0x87, 0x22, 0xe7, 0x8a, 0x93, 0x16, 0x15, 0x2c, 0xbc, 0x87, 0xde, 0xcd,
	0x0c, 0x93, 0x34, 0xc2, 0xb7, 0x05, 0x4a, 0x45, 0xfa, 0xd0, 0x9e, 0xf3, 0x17, 0x96, 0xf9, 0xcd,
	0xe3, 0xe6, 0xe9, 0xef, 0xa8, 0x38, 0x90, 0x00, 0xba, 0x82, 0x4a, 0xf9, 0xce, 0xf3, 0xa9, 0xef,
	0xe9, 0x87, 0xf2, 0x4c, 0xfe, 0x82, 0xc7, 0x84, 0xdf, 0xd2, 0xb7, 0x1e, 0x13, 0xe1, 0x11, 0xfc,
	0x31, 0x44, 0x29, 0x78, 0x26, 0x71, 0x15, 0xe0, 0xa9, 0xe6, 0x75, 0x23, 0x8f, 0xa7, 0xe1, 0x35,
	0xf4, 0x22, 0x94, 0xa8, 0xbe, 0xff, 0xc9, 0x02, 0xeb, 0xd9, 0x58, 0x33, 0x55, 0x83, 0x3d, 0x87,
	0x9d, 0xc9, 0x9c, 0x26, 0xe9, 0x9c, 0x49, 0x35, 0x9e, 0x4e, 0xbf, 0xe8, 0x03, 0xe8, 0xc8, 0x45,
	0x9c, 0xa1, 0x32, 0x78, 0x73, 0x0a, 0x4f, 0xa0, 0x5f, 0x8d, 0xd7, 0x60, 0x47, 0x30, 0x28, 0x73,
	0x11, 0xbe, 0xf2, 0x25, 0xfe, 0x44, 0x3e, 0x83, 0xbd, 0x8d, 0x89, 0xfa, 0xce, 0x8f, 0x33, 0xa6,
	0x70, 0xfb, 0xce, 0xd5, 0x78, 0x7d, 0xe7, 0x32, 0xb7, 0x75, 0xe7, 0x8d, 0x09, 0x37, 0xfc, 0xf2,
	0xa3, 0x05, 0xbb, 0xe3, 0x4c, 0xb1, 0x49, 0xb9, 0x4f, 0x0f, 0x98, 0x2f, 0x59, 0x82, 0x64, 0x04,
	0x6d, 0x6d, 0x9e, 0xfc, 0x1f, 0x52, 0xc1, 0x86, 0xf6, 0x5e, 0x05, 0xc4, 0xbe, 0x2a, 0xc8, 0x61,
	0x63, 0x35, 0xa1, 0xa5, 0x9a, 0x09, 0x7b, 0x2d, 0xcc, 0x44, 0xc5, 0x79, 0xd8, 0x20, 0xb7, 0xd0,
	0xb3, 0xb5, 0x11, 0x5f, 0xa7, 0x1c, 0xe2, 0x83, 0x7d, 0xc7, 0x4b, 0x89, 0xb9, 0x83, 0x7f, 0x6b,
	0x8e, 0xc8, 0x41, 0x35, 0x5f, 0xf9, 0xdf, 0x82, 0x43, 0xf7, 0xa3, 0x5d, 0xcb, 0x36, 0x63, 0x6a,
	0x39, 0xdc, 0x9a, 0x5a, 0x2e, 0x8d, 0x45, 0xad, 0x35, 0x0d, 0xa6, 0x96, 0x5b, 0xa7, 0xa9, 0x55,
	0x63, 0x2e, 0x6c, 0x4c, 0x7e, 0x3d, 0xb5, 0xa9, 0x60, 0x22, 0x8e, 0x3b, 0xfa, 0x93, 0xbf, 0xfa,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0x80, 0x78, 0xf8, 0xda, 0x0e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AntiBruteforceServiceClient is the client API for AntiBruteforceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AntiBruteforceServiceClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	BlacklistAdd(ctx context.Context, in *BlacklistAddRequest, opts ...grpc.CallOption) (*BlacklistAddResponse, error)
	BlacklistRemove(ctx context.Context, in *BlacklistRemoveRequest, opts ...grpc.CallOption) (*BlacklistRemoveResponse, error)
	WhitelistAdd(ctx context.Context, in *WhitelistAddRequest, opts ...grpc.CallOption) (*WhitelistAddResponse, error)
	WhitelistRemove(ctx context.Context, in *WhitelistRemoveRequest, opts ...grpc.CallOption) (*WhitelistRemoveResponse, error)
}

type antiBruteforceServiceClient struct {
	cc *grpc.ClientConn
}

func NewAntiBruteforceServiceClient(cc *grpc.ClientConn) AntiBruteforceServiceClient {
	return &antiBruteforceServiceClient{cc}
}

func (c *antiBruteforceServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) BlacklistAdd(ctx context.Context, in *BlacklistAddRequest, opts ...grpc.CallOption) (*BlacklistAddResponse, error) {
	out := new(BlacklistAddResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/BlacklistAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) BlacklistRemove(ctx context.Context, in *BlacklistRemoveRequest, opts ...grpc.CallOption) (*BlacklistRemoveResponse, error) {
	out := new(BlacklistRemoveResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/BlacklistRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) WhitelistAdd(ctx context.Context, in *WhitelistAddRequest, opts ...grpc.CallOption) (*WhitelistAddResponse, error) {
	out := new(WhitelistAddResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/WhitelistAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) WhitelistRemove(ctx context.Context, in *WhitelistRemoveRequest, opts ...grpc.CallOption) (*WhitelistRemoveResponse, error) {
	out := new(WhitelistRemoveResponse)
	err := c.cc.Invoke(ctx, "/api.AntiBruteforceService/WhitelistRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServiceServer is the server API for AntiBruteforceService service.
type AntiBruteforceServiceServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	BlacklistAdd(context.Context, *BlacklistAddRequest) (*BlacklistAddResponse, error)
	BlacklistRemove(context.Context, *BlacklistRemoveRequest) (*BlacklistRemoveResponse, error)
	WhitelistAdd(context.Context, *WhitelistAddRequest) (*WhitelistAddResponse, error)
	WhitelistRemove(context.Context, *WhitelistRemoveRequest) (*WhitelistRemoveResponse, error)
}

// UnimplementedAntiBruteforceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAntiBruteforceServiceServer struct {
}

func (*UnimplementedAntiBruteforceServiceServer) Check(ctx context.Context, req *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedAntiBruteforceServiceServer) Reset(ctx context.Context, req *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedAntiBruteforceServiceServer) BlacklistAdd(ctx context.Context, req *BlacklistAddRequest) (*BlacklistAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlacklistAdd not implemented")
}
func (*UnimplementedAntiBruteforceServiceServer) BlacklistRemove(ctx context.Context, req *BlacklistRemoveRequest) (*BlacklistRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlacklistRemove not implemented")
}
func (*UnimplementedAntiBruteforceServiceServer) WhitelistAdd(ctx context.Context, req *WhitelistAddRequest) (*WhitelistAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhitelistAdd not implemented")
}
func (*UnimplementedAntiBruteforceServiceServer) WhitelistRemove(ctx context.Context, req *WhitelistRemoveRequest) (*WhitelistRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhitelistRemove not implemented")
}

func RegisterAntiBruteforceServiceServer(s *grpc.Server, srv AntiBruteforceServiceServer) {
	s.RegisterService(&_AntiBruteforceService_serviceDesc, srv)
}

func _AntiBruteforceService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_BlacklistAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).BlacklistAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/BlacklistAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).BlacklistAdd(ctx, req.(*BlacklistAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_BlacklistRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).BlacklistRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/BlacklistRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).BlacklistRemove(ctx, req.(*BlacklistRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_WhitelistAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).WhitelistAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/WhitelistAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).WhitelistAdd(ctx, req.(*WhitelistAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_WhitelistRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).WhitelistRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AntiBruteforceService/WhitelistRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).WhitelistRemove(ctx, req.(*WhitelistRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AntiBruteforceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AntiBruteforceService",
	HandlerType: (*AntiBruteforceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AntiBruteforceService_Check_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _AntiBruteforceService_Reset_Handler,
		},
		{
			MethodName: "BlacklistAdd",
			Handler:    _AntiBruteforceService_BlacklistAdd_Handler,
		},
		{
			MethodName: "BlacklistRemove",
			Handler:    _AntiBruteforceService_BlacklistRemove_Handler,
		},
		{
			MethodName: "WhitelistAdd",
			Handler:    _AntiBruteforceService_WhitelistAdd_Handler,
		},
		{
			MethodName: "WhitelistRemove",
			Handler:    _AntiBruteforceService_WhitelistRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/antibruteforce.proto",
}
