// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import time "time"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, key, capacity, rate
func (_m *Repository) Add(ctx context.Context, key string, capacity uint, rate time.Duration) error {
	ret := _m.Called(ctx, key, capacity, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, time.Duration) error); ok {
		r0 = rf(ctx, key, capacity, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reset provides a mock function with given fields: ctx, keys
func (_m *Repository) Reset(ctx context.Context, keys []string) error {
	ret := _m.Called(ctx, keys)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
