pg_stat_user_tables:
  query: select current_database() as datname, n_live_tup as blacklist_count from antibruteforce.pg_catalog.pg_stat_user_tables where relname='blacklist'
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - blacklist_count:
        usage: "COUNTER"
        description: "Blacklist count"
